name: suql
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - openai==1.3.2
    - Jinja2==3.1.2
    - Flask==2.3.2
    - Flask-Cors==4.0.0
    - Flask-RESTful==0.3.10
    - requests==2.31.0
    - spacy==3.7.4
    - tiktoken==0.4.0
    - psycopg2-binary==2.9.7  # you can also install from source if it works
    - pglast==5.3
    - FlagEmbedding==1.2.5